### ISSUE TITLE
Abstract out contract logic for better testing and benchmarking

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#143]
Testing for individual contract function is difficult because it usually depends on other contract states.

For example, before we test submitBatch, we have to initialize a governance contract in the constructor. So it's hard to wrap the submitBatch in a TestRollup.sol and test/benchmark it properly.

```
function submitBatch(...) {
    // depends on governance contract, so need to deploy governance contract to test this function
    require(leaves.length <= governance.MAX_TXS_PER_BATCH())
}

```

We should instead separate the `submitBatch` function into two parts. The outer part depends on the `governance` contract, and the inner part doesn't. So that the inner part can be better tested.

```
function submitBatch(...) {
    _submitBatch(..., governance.MAX_TXS_PER_BATCH())
}

function _submitBatch(..., max_tx_per_batch) {
    // This can be tested without governance contract
    require(leaves.length <= max_tx_per_batch)
}
```

**Comment by vaibhavchellani** [comment]
Maybe, instead of reading from gov contract, we should have that variable on rollup contract and allow only Gov contract to update it

**Comment by ChihChengLiang** [comment]
>  have that variable on rollup contract and allow only Gov contract to update it

That's a great idea!
