### ISSUE TITLE
Fix DepositManager

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#161]
Due to the pressing deadline, we are letting a user register their public key via a direct call to the BLSAccountRegistry contract's register function.

This saves the effort to handle the on-chain token transfer logic.

We have to bring back DepositManager when we have time.

**Comment by vaibhavchellani** [comment]
I think we still have DepositManager, its just that before it used to register public key and do a deposit, now there are 2 functions, one for registering a new account and one for doing a deposit. I think we should keep separate both the functions as they are now and just have one other utility function that does `createAccountAndDeposit` to have the flow as before.

**Comment by ChihChengLiang** [comment]
Resolved in #245 and #246
