### ISSUE TITLE
Double withdraw in `vault.requestApproval`

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#263]
### What's wrong

ProcessWithdrawCommitment can request token from Vault again and again with the same mass migration proof.

### How can it be fixed

Vault should remember if it has approved a commitment before.
`vault.requestApproval(_batch_id, commitmentMP);`

Maybe a bitmap of batchID => commitmentID

**Comment by vaibhavchellani** [comment]
Ah I see, so we need 2 kind of storage maps here
- On the vault side, commitment level
- On the withdraw manager side, tx level

So a bitmap sounds good to me as we will be doing something similar in #255
