### ISSUE TITLE
Attackers can slash the first commitment in the batch with previous commit

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#265]
### What's wrong

To dispute the first commitment in the batch, we require the challenger to provide the last commit in the previous batch. However, we currently only require that commit to be in the previous batch but have no way to make sure that's the last commit.

So if the previous batch has 3 commits, an attacker can provide the second commit with proofs to trick the dispute function that the target commit is fraudulent.  

https://github.com/thehubbleproject/hubble-contracts/blob/c0228fbda6951257cb27b84dbd9ca81708491703/contracts/Rollup.sol#L105-L110

### How could we fix it
We need to commit the number of commits in a batch somewhere so that we can check if a previous commit is a last commit in the batch.

**Comment by vaibhavchellani** [comment]
Can we use the number of siblings to determine the number of commitments?

**Comment by ChihChengLiang** [comment]
The number of siblings might not work. A witness of 5 levels could mean you have 17~32 commitments.

**Comment by ChihChengLiang** [comment]
On a second thought, it might be possible. 
if path is 1 << witness.length, then the leaf is the last. 

if path is less than 1 << (witness.length -1), it is impossible to be the last (unless it's a 1 leaf special case)

if the path is in between, then we can calculate a certain node in the witness must be one of the zero hashes.
if at the current level the path is odd, then the right node is zero[level]. if the path is even, we ascend and check again.

**Comment by vaibhavchellani** [comment]
Yeah, it seems possible, but if its simpler to commit we can do that too since the cost of doing that is low.

**Comment by ChihChengLiang** [comment]
Yeah, committing sounds about right. A simple merkle proof verification costs 14k gas, but the verify the last leaf costs 66k (the overhead might come from reading the zero hash). And the readability looks worse than a simple commit. There might be other gotchas too.

The only question is I'm not sure where's the best place to commit the value.
