### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#275]
- We should log the state root for each commitment.
- ~~batchType is no longer meaningful. Should change it to commitment type~~ (Updated)

**Comment by vaibhavchellani** [comment]
Why isnt batch type meaningful?

**Comment by ChihChengLiang** [comment]
Ah, nevermind, the batch type is still meaningful. The batch still contains the same types of disputables.

**Comment by vaibhavchellani** [comment]
Why should we log commitment roots? A

**Comment by ChihChengLiang** [comment]
Oh, are we getting the state roots from the calldata?

**Comment by vaibhavchellani** [comment]
Well TBH these changes arent implemented on node yet, but yeah the plan is to get stateRoots from the calldata and then run txs on the node and finally match stateRoots

**Comment by ChihChengLiang** [comment]
So our offline discussion yesterday concludes that we might need just only batch index and commitmentRoot logged. Let's revisit when we work on the node.
