### ISSUE TITLE
Client frontend contract

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#280]
Plan to move all node related contracts (which has no business on chain) to a single directory.

The client frontend contract should have these functions implemented:

# Hubble frontend contracts

- Transfer
    - processTx
    - applyTx
    - processFee
    - checkSignature

- Create2Tranfer
    - processTx(which takes encoded tx data and compresses it on contracts)
    - ApplyTx ( checks if tx.from == mp.account.path and routes to ApplyTxSender)
    - processFee
    - checkSignature

- Mass Migrations
    - processTx
    - ApplyTx
    - processFee (not ready on contract yet)

## Notes 
- ApplyTx wraps ApplyTxSender and ApplyTransferTxReceiver
- ProcessTx on frontend contracts takes encodedTxData and converts to Tx.Transfer on fly before routing to transfer.ProcessTx
- encodedTxData to compressed data should be in ProcessTx and ApplyTx

**Comment by vaibhavchellani** [comment]
Can you assign this to someone?  I can take it up if you have tasks at hand

**Comment by ChihChengLiang** [comment]
Fixed partially in #282

**Comment by ChihChengLiang** [comment]
closing in favor of #291
