### ISSUE TITLE
Add accountRegistry to clientFrontend

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-contracts#291]
The client needs access to accountRegistry for create2transfer to work.

**Comment by ChihChengLiang** [comment]
We need accountRegistry but clientFrontend might not be the best place for it. Since accountRegistry is an on chain function, putting it in clientFrontend would incur an extra gas cost.

**Comment by vaibhavchellani** [comment]
Yeah I agree, just wanted to mention that we need it exposed to client, any place is good for me :))

**Comment by ChihChengLiang** [comment]
validateAndApplyX let us do the state transition. But we also need to add processX API to be comfortable with the correctness of the merkle proof.

**Comment by ChihChengLiang** [comment]
Need 
1. account tree check (we could use `exists` API from the Pubkey Tree)
2. checksignature (add to frontend contract)

**Comment by ChihChengLiang** [comment]
Looks like mostly addressed. Feel free to create a new issue for further requests on the client frontend.
