### ISSUE TITLE
Add single function to register pubkey and do a deposit

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-contracts#318]

**Comment by ChihChengLiang** [comment]
Can we elaborate on this? Not sure what exactly to do about this issue.

**Comment by vaibhavchellani** [comment]
We want to have a single helper function that registers a pubkey using the register method in BLSAccountRegistry and does a depositFor in depositManager.sol

**Comment by ChihChengLiang** [comment]
Got it. It looks like we could have a subdirectory of contracts that implement these inter-contract wrappers so that we could exclude them from the auditing scope.

**Comment by vaibhavchellani** [comment]
Think we should have these contracts in the audit scope as these would be used by the frontend or other integrators.
