### ISSUE TITLE
Allow dynamic pubkey batch size

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-contracts#350]
Would be great if we could allow dynamic size of pubkeys while [registering](https://github.com/thehubbleproject/hubble-contracts/blob/master/contracts/BLSAccountRegistry.sol#L16) instead of the current 1024.

**Comment by ChihChengLiang** [comment]
Need some more time to know if the dynamic size would break anything. But as a low hanging fruit, we can adjust the size to a  smaller power of 2.
