### ISSUE TITLE
One can slash a coordinator if they include 2 or more txs with the same sender

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#382]
### What's wrong

In the signature check, we recover the signing message with the committed tx data and a nonce.

The nonce is acquired from the state. The disputer provides the state corresponding to the post-state root. The Authenticity contract checks if the state is indeed included in that state root, and subtract 1 from that state's nonce to get the correct signing nonce.

The problem is the 2 post states that the disputer provides will be the same state.

Say, a sender sends 2 transfers with nonce 0 and 1, and those were included in a commitment. The post-state of the sender of that commitment is 2. The disputer provides the same states, and the Authenticity contract computes Merkle inclusion check, then concludes the signing nonce should be 1. The first tx whose nonce is 0 will fail the signature check.

### How can we fix it

In the coordinator implementation, never includes 2 txs with the same sender in a commitment.

**Comment by ChihChengLiang** [comment]
Summarizing the discussion with @kilic here.
We are exploring ways that can do better than forbidding the coordinator to send multiple transactions with the same sender.

The idea is to deduct correct nonce in the signature check fraud-proof. If we are able to do an in-memory mapping, then we can track how many times we've seen a sender. 

We can iterate the transactions backward. If a transaction T has the end state nonce 2, but we've seen the same sender before once. Then we know the previous transaction corresponds to nonce 1, and this transaction T has nonce 0.

But since we don't have in-memory mapping, a naive O(n^2) approach would be tracking the sender in an array of the same size as the committed transactions. We loop through the array to see how many identical senders we've met and we derive the correct nonce.

**Comment by kilic** [comment]
> But since we don't have in-memory mapping, a naive O(n^2) approach would be tracking the sender in an array of the same size as the committed transactions. We loop through the array to see how many identical senders we've met and we derive the correct nonce.

I think we should calculate how much gas it would take for whole batch. Since our batches are small for now this approach might not come with significant cost.
