### ISSUE TITLE
Create deploy scripts for Registering Tokens and Fee Receivers

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#390]
### What's wrong

When we deploy the system, we want to 
- Register a list of token of interest
- Deposit for coordinators so they can collect fees for those tokens

### How can we fix it

- Create a config that has a list of addresses and the name of the token (maybe also tokenID)
- add a script that does a mass deposit for coordinators

### Problem

The deposit manager currently requires a non-zero amount. Do coordinators really need to have all the shitcoins to do the deposit?

**Comment by vaibhavchellani** [comment]
> Do coordinators really need to have all the shitcoins to do the deposit?

Good question. So far there are 2 ways to create a new state leaf, deposits or create2transfer and amongst them, only one way to enter L2 with a new token i.e `deposit` so it does seem like the coordinator has to have a state leaf for every shitcoin he wants to accept fees in

**Comment by ChihChengLiang** [comment]
What do you think we allow 0 amount but charge a Eth fee to deposit?

**Comment by vaibhavchellani** [comment]
Ah! That's interesting, but the deposit manager won't allow that, would it?

**Comment by ChihChengLiang** [comment]
Close this in favor of the new one  #476
