### ISSUE TITLE
Add missing stuffs to Genesis config

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#397]
- add a genesis eth1 block, so that client knows where to sync to.
- add a list of genesis states. So that client can know what's behind the genesis state and can check against the genesis root.

- figure out how to sync the genesis account tree. 
  - In the dev environment, we might have an account tree that's deployed at genesis. So naively we write genesis public keys to the genesis file.
  - But there are situations we want to use the most popular account tree, maybe we want to specify the genesis of that account tree and sync logs from there.

**Comment by vaibhavchellani** [comment]
Agree with the first bullet but looks like the second and third one are dev/testing related in which case we should make accommodations on the client and keep the genesis clean

**Comment by ChihChengLiang** [comment]
Sounds good. Though I disagree that second and third one are dev/testing related only, we don't have a good use case that requires us to have non-empty genesis states now.

**Comment by vaibhavchellani** [comment]
That makes a lot of sense to me.

**Comment by ChihChengLiang** [comment]
Oh, we should add a signing domain too.
I'm considering creating an "auxiliary" section in the genesis.json to distinguish from the "parameters". Values in the auxiliary are known after the deployment.
We can add genesisBlock and signing domain here.

**Comment by vaibhavchellani** [comment]
Perfect, sounds good.
