### ISSUE TITLE
[Audit] Use extended Euclidean algorithm to compute modular inverse

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#399]
https://github.com/thehubbleproject/hubble-contracts/blob/32234da0ce3015b4bece04a264a136a6778191dd/contracts/libs/ModExp.sol
> We propose using more efficient extended Euclidean algorithm.

**Comment by kilic** [comment]
Compared EEA inversion against modexp method. Seems like EEA is much expensive than modexp. 

* [EEA in sol](https://github.com/thehubbleproject/hubble-contracts/blob/inv-cost/contracts/libs/Inv.sol)
* [Benchmark](https://github.com/thehubbleproject/hubble-contracts/blob/inv-cost/test/inversion.test.ts)

**Comment by kilic** [comment]
Also I need to add that we know that with square root and inversion helpers we can cut hashing cost down to 1k gas. see example implementation [here](https://github.com/kilic/evmbls/blob/54c3e8f269b2bafa02a4e4969d0e976ecb2ce04a/contracts/BLS.sol#L99).

**Comment by ChihChengLiang** [comment]
We conclude that the extended Euclidean algorithm is not cheaper in gas cost than the existing add chain method.
