### ISSUE TITLE
Run the mining script in background

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-contracts#410]
The client doesn't receive any logs till the transaction is under X blocks so we have a script that sends `evm_mine` to mine blocks on hardhat, we want to run that script continuously in the background instead of manually to replicate normal behavior.

**Comment by ChihChengLiang** [comment]
A quick hack is 

```
watch -n 0.5 'npx ts-node ./scripts/mineBlocks.ts -n 5'
```

in mac you can install with 
```
brew install watch
```

**Comment by vaibhavchellani** [comment]
that's a good one, I think I'll just use that and close this issue.
