### ISSUE TITLE
Verification failure when 4 or less signatures are aggregated.

### ISSUE THREAD

**Issue by jzaki** [thehubbleproject/hubble-contracts#417]
https://github.com/thehubbleproject/hubble-contracts/blob/3c6e39b2b0f1b7969ae4be90fdb4fa0036735644/test/fast/bls.test.ts#L67
I didn't come across a documented minimum.

**Steps**:
- set `n = 4` (or 2, 3)
- run tests

**Result**: Verification fails. **Expect**: Verification to succeed

**Comment by ChihChengLiang** [comment]
Nice catch! Looks like the miscalculation of the gas cost cause it. 
https://github.com/ethereum/go-ethereum/blob/master/params/protocol_params.go#L127

**Comment by ChihChengLiang** [comment]
Sending a fix #418. Thank you @jzaki for finding this issue

**Comment by ChihChengLiang** [comment]
Fixed in #418. Feel free to reopen if you find it doesn't work
