### ISSUE TITLE
Reduce register pubkey batch sizes

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-contracts#464]
The current implementation allows batch register of 16pubkeys which means that the coordinator needs to wait for 16 new create2txs before he can register the batch on-chain and process the transaction. 

This means that once the user uses create2transfer to send someone payment his normal transfers won't get processed till the create2transfer goes through.

**Comment by vaibhavchellani** [comment]
Can we have multiple register batches for different sizes?

**Comment by ChihChengLiang** [comment]
Yeah, that sounds like a good idea. I propose we

1. Restore the account tree batch register size back to 1024 pubkeys. The batch register was designed to onboard a lot of users.
2. Create a medium size solution for our usual use cases.

The medium size solution is a contract wrapper that call AccountTree.registerSingle serval times. So we can save the 21000 gas for base ETH1 tx.

**Comment by ChihChengLiang** [comment]
Keep the status quo before the devnet
