### ISSUE TITLE
Scripts to add 4 tokens and fee receivers for dev case

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#476]

**Comment by jacque006** [comment]
@ChihChengLiang Can this be closed in favor of https://github.com/thehubbleproject/hubble-contracts/issues/557? Or is this for setting up the contract where those are stored?

**Comment by ChihChengLiang** [comment]
Yes, this is for some more stuff.

1. setting up the contracts to register 4 tokens in the tokenRegistry
2. revamping the txpool to support multiple token.
3. (optional) figure out how to compare token fees between different tokens. Need a price feed for this. We could defer this by using a more naive strategy like serving each token one by one.

**Comment by jacque006** [comment]
Multi token tx pool broken off into https://github.com/thehubbleproject/hubble-contracts/issues/626
