### ISSUE TITLE
Ownership of tokenRegistry

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#479]
### What's wrong

We haven't defined who can register and finalize the token registration.

We probably want to freeze the registration after deployment. Or we might want to have a centralized owner who can determine the registration.

### How can we fix it

Add ownable

**Comment by jacque006** [comment]
@ChihChengLiang Why do we not want anyone to be able to register a token? Is it quality control to prevent less reputable tokens from being added?

**Comment by ChihChengLiang** [comment]
I know people kind of control the addition of new tokens with some governance mechanism. [example](https://github.com/hermeznetwork/contracts/blob/master/contracts/hermez/Hermez.sol#L682)

But I don't really have a good reason to support whether we should restrict this or not for now.

**Comment by ChihChengLiang** [comment]
close in favor of #584
