### ISSUE TITLE
SpokeRegistry has no access control

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#488]

**Comment by jacque006** [comment]
@ChihChengLiang What would need to be modified in the `SpokeRegistry` contract to to provide access control? Is there an example in this codebase or another project?

**Comment by ChihChengLiang** [comment]
Adding an Ownable contract from openzepplin. 

But this task is blocked by I haven't figured out "who should own it".

**Comment by ChihChengLiang** [comment]
close in favor of #584
