### ISSUE TITLE
Use withdraw pattern in the rollback

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#498]
### What's wrong

Currently, in our rollback function, we directly send the reward to the disputer. This frontrunner can detect balance change easily and front-run a rollback.
```
    function rollback() internal {
       ...
        msg.sender.transfer(reward);
        address(0).transfer(burn);
    }
```
### How can we fix it

We instead define a `rewards` mapping. The rollback tracks how much reward owes to the disputer, then the disputer can claim the reward by themself.

```
    function rollback() internal {
       ...
        rewards[msg.sender] += reward; // edited
        address(0).transfer(burn);
    }

    function claimReward(){
        require(rewards[msg.sender] > 0, "No reward for this claimer");
        msg.sender.transfer(reward);
    }
```

Pros: Watchers are less discouraged to watch.
Cons: Frontrunners are less excited to rush that fraudproof on-chain.

Note: We had this discussion https://github.com/thehubbleproject/hubble-contracts/discussions/444. It says it is desired for frontrunners to outbid the watcher to make a fraudproof seen on chain sooner.

**Comment by snjax** [comment]
There are enough smart front-run bots, they will interpret claimable `rewards[]` as balances. Anyway, the update of the reward should be additive `rewards[msg.sender] += reward;`

The safest way to protect from the front-run is the commit-reveal scheme but is sophisticated.
1. disputer commit hashes
2. disputer reveal hashes
3. the earliest committer for the same point gets the bond

**Comment by snjax** [comment]
Also, all disputers reward could be put into timelock contract, it could protect from smart bots, who try to reach the reward immediately.

For a general bot, there is a risk, that locked money should not be withdrawable for any purposes, that's why the general bot (not specially developed for the hubble) will not front-run such transactions.

**Comment by ChihChengLiang** [comment]
Thanks for the quick inputs and the good strategies for front-run protection.
It looks like the withdrawal pattern does not change the arm-race game too much and we still want the frontrunner to compete for the fraud-proof. Let's stay with the status quo.
