### ISSUE TITLE
Event DepositQueued can be simplified

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#517]
### What's wrong

Event DepositQueued tells the client 3 pieces of information of a freshly created state: pubkeyID, tokenID, and l2Amount. The nonce is always 0, so not required.

The current DepositQueued contains fields of unuseful and redundant information. pubkey 1 word and encodedState is probably 5 words (1 for the length of bytes and 4 for the contents of state)

https://github.com/thehubbleproject/hubble-contracts/blob/f7666140ef38b72b73d2ddd28825a8bf6705bbed/contracts/DepositManager.sol#L149

### How can we fix it

Ideally make it `event DepositQueued(uint32 pubkeyID, uint32 tokenID, uint128 l2Amount);` so it can be packed in 32 bytes.

**Comment by jacque006** [comment]
Note that in [depositFor](https://github.com/thehubbleproject/hubble-contracts/blob/master/contracts/DepositManager.sol#L131-L159), which emits `DepositQueued` the new event args are all `uint256` in function.

@ChihChengLiang given that increased size, do we still want to update the `DepositQueued` event? Or am I missing something here?

**Comment by ChihChengLiang** [comment]
Ah sorry, my description is confusing. 

The existing `DepositQueued` emits unnecessary information. It's ok we still use uint256 in the `DepositQueued` event. But we shouldn't have the encodedState field as what it is now. The reason is encodedState is the pubkeyID+tokenID+balance+nonce, where pubkeyID is duplicated information and nonce is unhelpful as it should always be 0.
