### ISSUE TITLE
Add public key and deposit to the syncer

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#532]
### What's wrong

Syncer now sync only batches. But they need to sync registered public keys and submitted deposits too.

### How can we fix it?

- parse deposit events, push deposit leaf to deposit pool
- parse public key events, push public keys to storageManager.pubkey

**Comment by jacque006** [comment]
@ChihChengLiang Given https://github.com/thehubbleproject/hubble-contracts/issues/553 , do we still need the public key syncing in this issue?
Is the deposit sync here work split off from https://github.com/thehubbleproject/hubble-contracts/issues/519 or something different?

**Comment by ChihChengLiang** [comment]
> Given #553, do we still need the public key syncing in this issue?

We don't. Public key syncing is addressed in #553.

> Is the deposit sync here work split off from #519 or something different?

deposit sync refers to this description in #519


- The client listens to L1 deposit events and builds subtree locally. Specifically:
  - listen to the deposit manager for the DepositQueued event. The event arguments contain the state leaf data. The client memorizes those state leaves.
  - listen to the deposit manager for the DepositSubTreeReady event. When a subtree is ready, a subtree root and a subtreeID are emitted. The client builds the subtree from the state leaves they memorized before.

**Comment by jacque006** [comment]
As part of this work, remove deposit pool verification in `test/fast/deposit.test.ts` in favor of testing validity via sync integration tests.
