### ISSUE TITLE
Add history storage

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#548]
### What's wrong

We need a set of history storage for batches and different type of messages.

- Batch history API
  - Proposer of deposit needs a previous batch to propose
  - Watcher needs the previous batch to prove the pre root of a fraudulent batch

- Transaction history API
  - Let the user query if a tx has been finalized.
  - Provide tx receipt that has information of batch or block included

**Comment by jacque006** [comment]
Notes:
 - In memory (for now)
 - Support packing and submitDeposit

**Comment by jacque006** [comment]
Split batch/block included to https://github.com/thehubbleproject/hubble-contracts/issues/592
