### ISSUE TITLE
Circular Dependency Warning

### ISSUE THREAD

**Issue by jacque006** [thehubbleproject/hubble-contracts#555]
When running tests (`npm test`) and some scripts, the following NodeJS warning appears:
```bash
(node:41227) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```
Likely an issue with a dependency that needs to be updated or a bad import cycle in code.

**Comment by ChihChengLiang** [comment]
Yeah, this is an issue I've been wanting to address. NodeJS seems to allow some degree of circular dependency and raises no error for it.
Do you know any tool that we can detect the circular dependency? Or what's the best practice to do the import?

**Comment by jacque006** [comment]
Adding the `--trace-warnings` as a pass through arg (i.e. `npm test -- --trace-warnings`) should give the import stack trace. Also of note is that this mainly shows up for NodeJS 14 as they added better detection/warnings for circular deps. 

Found https://github.com/antlr/antlr4/issues/2834 which looks to be the culprit. Just need to find the lib we are using that has that as a dep and update it if possible.

**Comment by jacque006** [comment]
Actual issue: https://github.com/prettier-solidity/prettier-plugin-solidity/issues/335
