### ISSUE TITLE
Cheaper Create2Transfer fraudproof with keccak(pubkeyReceiver) as input

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#574]
Thank Phil Zip for finding this issue

### What's wrong

In the signature fraudproof of create2Transfer, we send the receiver's public key to the solidity function `verifyCreate2Transfer`. The receiver's public key is uint256[4] per key, which is more expensive than `keccak(pubkeyReceiver)` (uint256), which we are totally able to do it. This would save us [16](https://github.com/ethereum/go-ethereum/blob/bbb57fd64b70e3c843b5171d0a4719cf457374fc/params/protocol_params.go#L77) * 32 * 3 gas per key from calldata.

https://github.com/thehubbleproject/hubble-contracts/blob/3bd33ce2c4b86d51b061babc2a50168193419c85/contracts/libs/Types.sol#L21

https://github.com/thehubbleproject/hubble-contracts/blob/3bd33ce2c4b86d51b061babc2a50168193419c85/contracts/libs/Authenticity.sol#L180-L181

#### Background

Create2transfers allows a sender to onboard a receiver who couldn't pay gas on L1. The flow looks like this

Step 1, the receiver generates key pairs and sends the public key to the Sender. Note that this step is not reflected in the codebase and doesn't have to be.
Step 2, sender signs and sends this message to the coordinator.

```
solidityPack(
            [ "uint256", "uint256", "uint256[4]", "uint256", "uint256", "uint256" ],
            [this.TX_TYPE, this.fromIndex, this.toPubkey, this.nonce,this.amount,  this.fee ]
        );
```
Step 3, the coordinator registers the receiver's public key, and the L1 gas is on the coordinator. The coordinator also gets a public key ID for the receiver.
Step 4, the coordinator submits the Create2transfers batch with the following message along with the sender's signature on-chain. Note that the coordinator finds a vacant position in the state tree and inserts the state leaf there. The new state leaf is the receiver's state leaf.

```
// [sender_state_id<4>|receiver_state_id<4>|receiver_acc_id<4>|amount<2>|fee<2>]
```

After all these the receiver now has a public key in the public key tree, a state index, and a state in the state tree. No gas is paid.

The state transition dispute is mostly the same as the Transfer's, with the difference being

1. The state index at the previous state is empty so that the coordinator is not overriding other people's states.
2. The created new state's pubkeyID matches `tx.toPubkeyID` so that the new state is spendable by the receiver.

The signature dispute checks additionally

1. The toPubkey signed by the sender matches key at the `tx.toPubkeyID` position in the public key tree. So that the coordinator can't fill in `tx.toPubkeyID` with some other keys.

### How can we fix it

The condition "The *toPubkey* signed by the sender matches *key* at the `tx.toPubkeyID` position in the public key tree." can be replaced with "The *hash(toPubkey)* signed by the sender matches *hash(key)* at the `tx.toPubkeyID` position in the public key tree."

We need to change 2 places

1. sender signs `hash(toPubkey)` instead of toPubkey. We need to change the `create2TransferMessageOf` in Tx.sol
2. change ` Types.SignatureProofWithReceiver` and `verifyCreate2Transfer` in `Authenticity.sol`

**Comment by jacque006** [comment]
Per discovery/conversation with @ChihChengLiang , going to use `bytes32` instead of `uint256`. `uint256[4]` -> `bytes32`.
