### ISSUE TITLE
Naive packing strategy 

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-contracts#581]
### What's wrong

In #572, we defined a naive packing strategy for the proposer to use in the devnet.

In the devnet we expect to have deposit and transfer implemented. 

### How we are fixing it

when choosing the next batch to pack, the coordinator 

1. check if a subtree is ready in the deposit pool. If yes, send deposit batch
2. If no, check transfer pool and pack Transfers.

**Comment by jacque006** [comment]
@ChihChengLiang I think the current Packing logic meets the requirements of this issue: https://github.com/thehubbleproject/hubble-contracts/blob/master/ts/client/services/packer.ts

If not, what changes do we need to make?

**Comment by ChihChengLiang** [comment]
Yeah, looks like it is the case. Feel free to close.

**Comment by jacque006** [comment]
Resolved in https://github.com/thehubbleproject/hubble-contracts/pull/599
